import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { format } from "date-fns";

export interface AuditRecord {
  signerAddress: string;
  txHash: string;
  timestampMs: number;
}

export async function appendAuditTrail(
  pdfBuffer: ArrayBuffer,
  documentId: string,
  records: AuditRecord[]
): Promise<Blob> {
  const pdfDoc = await PDFDocument.load(pdfBuffer);
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const courier = await pdfDoc.embedFont(StandardFonts.Courier);

  // Add a new page at the end of the PDF
  const page = pdfDoc.addPage();
  const { width, height } = page.getSize();

  const margin = 50;
  let cursorY = height - margin;

  // Draw Header
  page.drawText("CRYPTOGRAPHIC AUDIT TRAIL", {
    x: margin,
    y: cursorY,
    size: 24,
    font: helveticaBold,
    color: rgb(0.1, 0.1, 0.4),
  });
  cursorY -= 30;

  page.drawText(`Sui Document Object ID:`, {
    x: margin,
    y: cursorY,
    size: 10,
    font: helveticaBold,
  });
  
  page.drawText(documentId, {
    x: margin + 140,
    y: cursorY,
    size: 10,
    font: courier,
    color: rgb(0.3, 0.3, 0.3),
  });
  cursorY -= 40;

  // Draw Signatures
  page.drawText("Verified Blockchain Signatures:", {
    x: margin,
    y: cursorY,
    size: 14,
    font: helveticaBold,
  });
  cursorY -= 30;

  records.forEach((record, idx) => {
    // Draw Box
    page.drawRectangle({
      x: margin,
      y: cursorY - 60,
      width: width - margin * 2,
      height: 70,
      borderColor: rgb(0.8, 0.8, 0.8),
      borderWidth: 1,
      color: rgb(0.98, 0.98, 0.99),
    });

    page.drawText(`Signer ${idx + 1}: ${record.signerAddress}`, {
      x: margin + 15,
      y: cursorY - 15,
      size: 11,
      font: courier,
      color: rgb(0.1, 0.5, 0.2), // Green tint for verified
    });

    page.drawText(`Timestamp: ${format(new Date(record.timestampMs), "PPpp")} (Network Consensus)`, {
      x: margin + 15,
      y: cursorY - 35,
      size: 10,
      font: helveticaFont,
    });

    page.drawText(`Tx Hash: ${record.txHash}`, {
      x: margin + 15,
      y: cursorY - 50,
      size: 9,
      font: courier,
      color: rgb(0.4, 0.4, 0.4),
    });

    cursorY -= 85;
  });

  page.drawText("Generated by TorrentSign Protocol", {
    x: margin,
    y: 50,
    size: 9,
    font: helveticaFont,
    color: rgb(0.5, 0.5, 0.5),
  });

  const modifiedPdfBytes = await pdfDoc.save();
  return new Blob([modifiedPdfBytes], { type: "application/pdf" });
}
